esphome:
  name: wren-c5

esp32:
  board: esp32-c5-devkitc-1 
  variant: esp32c5
  framework:
    type: esp-idf

# WREN C5 Test

i2c:
  sda: GPIO2
  scl: GPIO3
  scan: true

switch:
  - platform: gpio
    id: rs485_enable
    pin: GPIO23
    restore_mode: ALWAYS_ON  

output:
  - platform: gpio
    pin: GPIO27
    id: blue_led

light:
  - platform: binary
    output: blue_led
    id: heartbeat

interval:
  - interval: 500ms
    then:
      - light.toggle: heartbeat

binary_sensor:
  - platform: gpio
    id: in_1a
    name: "IN 1A"
    pin:
      number: GPIO8
      mode:
        input: true
        pulldown: true

    on_press:
      - logger.log: "IN_1A ON"

    on_release:
      - logger.log: "IN_1A OFF"        

  - platform: gpio
    id: in_1b
    name: "IN 1B"
    pin:
      number: GPIO9
      mode:
        input: true
        pulldown: true
        
    on_press:
      - logger.log: "IN_1B ON"

    on_release:
      - logger.log: "IN_1B OFF"        

  - platform: gpio
    id: in_2a
    name: "IN 2A"
    pin:
      number: GPIO14
      mode:
        input: true
        pulldown: true
        
    on_press:
      - logger.log: "IN_2A ON"

    on_release:
      - logger.log: "IN_2A OFF"

  - platform: gpio
    id: in_2b
    name: "IN 2B"
    pin:
      number: GPIO13
      mode:
        input: true
        pulldown: true
        
    on_press:
      - logger.log: "IN_2B ON"

    on_release:
      - logger.log: "IN_2B OFF"        

  - platform: gpio
    id: sflag
    name: "Motor Driver Fault"
    pin:
      number: GPIO10
      mode:
        input: true
        pulldown: true

    on_press:
      - logger.log: "Motor Driver Fault ACTIVE"

    on_release:
      - logger.log: "Motor Driver Fault CLEARED"

  - platform: gpio
    id: en1
    name: "EN1"
    pin:
      number: GPIO5
      mode:
        input: true

    on_press:
      - logger.log: "EN1 ON"

    on_release:
      - logger.log: "EN1 OFF"

  - platform: gpio
    id: en2
    name: "EN2"
    pin:
      number: GPIO6
      mode:
        input: true

    on_press:
      - logger.log: "EN2 ON"

    on_release:
      - logger.log: "EN2 OFF"    

sensor:
  - platform: adc
    pin: GPIO4
    name: "Supply Voltage"
    attenuation: auto
    update_interval: 1s
    filters:
      - multiply: 44.4444      

  - platform: tmp102
    name: "Board Temperature"
    address: 0x4A
    update_interval: 10s          

# Enable Home Assistant API

logger:

api:
  encryption:
    key: "wpRoSCFY6EyL1dVRgLK0Y8VgaEnkMzv7Q2RPWz6dOTs="

ota:
  - platform: esphome
    password: "0fe134e07d92f95b9194d6d19807d619"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wren-C5-Test Fallback Hotspot"
    password: "TvK7hKo0fKDu"

captive_portal:         